-- =====================================================================
-- IT Hardware Maintenance Tracker - database schema
-- Run this ONCE in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query).
-- Safe to re-run: every statement is idempotent.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 1. Reference values
--    Kept as CHECK constraints (rather than lookup tables) so the list
--    stays obvious to a small team. To add a cleaner or a device type,
--    edit the constraint below AND src/lib/constants.js.
-- ---------------------------------------------------------------------

-- ---------------------------------------------------------------------
-- 2. Main table
-- ---------------------------------------------------------------------
create table if not exists public.assets (
  id                       uuid primary key default gen_random_uuid(),

  asset_ref                text not null,
  device_type              text not null,
  owner_name               text not null,
  department               text not null,

  date_cleaned             date,
  cleaned_by               text,
  notes                    text,

  -- Cleaning cadence. Defaults to the 6-month business rule but can be
  -- overridden per asset (e.g. a dusty workshop PC on a 3-month cycle).
  cleaning_interval_months integer not null default 6,

  -- Next Clean Due is STORED and generated by the database, so it can never
  -- drift from Date Cleaned and can be indexed / reported on outside the app.
  next_clean_due date generated always as (
    case
      when date_cleaned is null then null
      else (date_cleaned + make_interval(months => cleaning_interval_months))::date
    end
  ) stored,

  -- Optimistic-concurrency token, bumped by the trigger on every write.
  version                  integer not null default 1,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid references auth.users(id) on delete set null,
  updated_by               uuid references auth.users(id) on delete set null,
  -- Denormalised so the UI can show "last updated by" without querying auth schema.
  updated_by_email         text,

  constraint assets_asset_ref_not_blank    check (btrim(asset_ref) <> ''),
  constraint assets_asset_ref_length       check (char_length(asset_ref) <= 40),
  constraint assets_owner_not_blank        check (btrim(owner_name) <> ''),
  constraint assets_department_not_blank   check (btrim(department) <> ''),
  constraint assets_device_type_valid      check (device_type in ('Laptop', 'Desktop')),
  constraint assets_cleaned_by_valid       check (cleaned_by is null or cleaned_by in ('AL', 'BB', 'JS', 'RC', 'TM')),
  -- "Cleaned By" and "Date Cleaned" only make sense together.
  constraint assets_clean_record_complete  check (
    (date_cleaned is null and cleaned_by is null)
    or (date_cleaned is not null and cleaned_by is not null)
  ),
  constraint assets_interval_range         check (cleaning_interval_months between 1 and 60),
  constraint assets_notes_length           check (notes is null or char_length(notes) <= 2000)
);

comment on table public.assets is 'IT hardware assets and their cleaning/maintenance history.';
comment on column public.assets.next_clean_due is 'Generated: date_cleaned + cleaning_interval_months. Never written by the client.';
comment on column public.assets.version is 'Incremented on every write; used for optimistic concurrency control.';

-- ---------------------------------------------------------------------
-- 3. Indexes and constraints
--    Asset Ref is unique case-insensitively and ignoring surrounding
--    whitespace, so "lap-001", "LAP-001 " and "LAP-001" collide.
-- ---------------------------------------------------------------------
create unique index if not exists assets_asset_ref_unique_idx
  on public.assets (upper(btrim(asset_ref)));

create index if not exists assets_next_clean_due_idx  on public.assets (next_clean_due nulls first);
create index if not exists assets_department_idx      on public.assets (department);
create index if not exists assets_device_type_idx     on public.assets (device_type);
create index if not exists assets_cleaned_by_idx      on public.assets (cleaned_by);
create index if not exists assets_updated_at_idx      on public.assets (updated_at desc);

-- ---------------------------------------------------------------------
-- 4. Status calculation (single source of truth, in the database)
--      Never Cleaned -> no Date Cleaned recorded
--      Overdue       -> next_clean_due is in the past
--      Due Soon      -> next_clean_due is within the next 30 days
--      OK            -> more than 30 days remaining
-- ---------------------------------------------------------------------
create or replace function public.asset_status(p_date_cleaned date, p_next_clean_due date)
returns text
language sql
stable
set search_path = public
as $$
  select case
    when p_date_cleaned is null or p_next_clean_due is null then 'Never Cleaned'
    when p_next_clean_due < current_date                    then 'Overdue'
    when p_next_clean_due <= current_date + 30              then 'Due Soon'
    else 'OK'
  end;
$$;

-- The app reads from this view and writes to the table underneath it.
-- security_invoker keeps the caller's RLS policies in force through the view.
create or replace view public.assets_with_status
with (security_invoker = on) as
select
  a.*,
  public.asset_status(a.date_cleaned, a.next_clean_due) as status,
  (a.next_clean_due - current_date)                     as days_until_due
from public.assets a;

comment on view public.assets_with_status is 'assets + derived status/days_until_due. Read-only surface for the app.';

-- ---------------------------------------------------------------------
-- 5. Write trigger: normalisation, validation and audit stamping.
--    Clients cannot forge created_at / updated_by / version.
-- ---------------------------------------------------------------------
create or replace function public.handle_asset_write()
returns trigger
language plpgsql
-- security definer so the stamping works regardless of what the signed-in role
-- is allowed to touch in the auth schema. The function only ever rewrites the
-- row being written; it never reads or changes another table.
security definer
set search_path = public, auth, pg_temp
as $$
begin
  new.asset_ref  := btrim(new.asset_ref);
  new.owner_name := btrim(new.owner_name);
  new.department := btrim(new.department);
  new.notes      := nullif(btrim(coalesce(new.notes, '')), '');

  if new.date_cleaned is not null and new.date_cleaned > current_date then
    raise exception 'Date Cleaned cannot be in the future (%).', new.date_cleaned
      using errcode = 'check_violation';
  end if;

  if tg_op = 'INSERT' then
    new.created_at := now();
    new.created_by := auth.uid();
    new.version    := 1;
  else
    -- Preserve creation audit data regardless of what the client sent.
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.version    := old.version + 1;
  end if;

  new.updated_at       := now();
  new.updated_by       := auth.uid();
  new.updated_by_email := coalesce(auth.jwt() ->> 'email', new.updated_by_email);

  return new;
end;
$$;

drop trigger if exists assets_write_trigger on public.assets;
create trigger assets_write_trigger
  before insert or update on public.assets
  for each row execute function public.handle_asset_write();

-- ---------------------------------------------------------------------
-- 6. Row Level Security
--    Every signed-in member of the IT team shares one dataset.
--    Anonymous visitors get nothing at all.
-- ---------------------------------------------------------------------
alter table public.assets enable row level security;

drop policy if exists "assets_select_authenticated" on public.assets;
create policy "assets_select_authenticated"
  on public.assets for select
  to authenticated
  using (true);

drop policy if exists "assets_insert_authenticated" on public.assets;
create policy "assets_insert_authenticated"
  on public.assets for insert
  to authenticated
  with check (true);

drop policy if exists "assets_update_authenticated" on public.assets;
create policy "assets_update_authenticated"
  on public.assets for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "assets_delete_authenticated" on public.assets;
create policy "assets_delete_authenticated"
  on public.assets for delete
  to authenticated
  using (true);

-- Optional hardening: to restrict deletes to named admins, replace the delete
-- policy above with something like
--   using (auth.jwt() ->> 'email' in ('alice@example.com', 'bob@example.com'));

revoke all on public.assets              from anon;
revoke all on public.assets_with_status  from anon;
grant select, insert, update, delete on public.assets             to authenticated;
grant select                          on public.assets_with_status to authenticated;
grant execute on function public.asset_status(date, date) to authenticated;

-- ---------------------------------------------------------------------
-- 7. Realtime: push changes to every open browser tab so concurrent
--    users see each other's edits without refreshing.
-- ---------------------------------------------------------------------
do $$
begin
  alter publication supabase_realtime add table public.assets;
exception
  when duplicate_object then null;
  when undefined_object then null;  -- publication missing (self-hosted); ignore
end;
$$;

-- Realtime also needs the old row to identify deletes under RLS.
alter table public.assets replica identity full;
