-- =====================================================================
-- IT Hardware Maintenance Tracker — complete database setup
--
-- ONE script that builds the whole database: tables, generated columns,
-- constraints, indexes, status logic, audit triggers, the cleaning history
-- log, Row Level Security and Realtime.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste all of this ->
--   Run. It should finish with "Success. No rows returned".
--
-- WHEN TO USE IT
--   * A brand-new Supabase project: this is the only script you need. The
--     numbered migration files next to it are the history of how an older
--     database reached this same state; a new one does not need them.
--   * An existing database, however old: run it again. It adds whatever is
--     missing (the asset history, admin roles, the purchase-date rule for
--     Next Clean Due) and leaves everything else as it is.
--
-- IT NEVER DESTROYS DATA. Nothing here drops a table or deletes a row. The
-- only things dropped are the read-only view, policies, triggers and
-- constraints, each recreated immediately afterwards.
--
-- Reference lists (device types, locations, cleaners) are CHECK constraints
-- rather than lookup tables, so a small team can see the whole list at a
-- glance. To change one, edit the constraint here AND src/lib/constants.js.
-- =====================================================================

create extension if not exists pgcrypto;


-- =====================================================================
-- 1. The assets table
-- =====================================================================
create table if not exists public.assets (
  id                       uuid primary key default gen_random_uuid(),

  asset_ref                text not null,
  device_type              text not null,
  -- Nullable on purpose: an asset nobody holds is "unassigned", and blank is
  -- stored as NULL so there is exactly one way to represent "nobody has this".
  owner_name               text,
  department               text not null,

  location                 text,
  purchase_cost            numeric(12, 2),
  purchase_date            date,

  date_cleaned             date,
  cleaned_by               text,
  notes                    text,

  -- Cleaning cadence. Defaults to the 6-month business rule but can be
  -- overridden per asset (e.g. a dusty workshop PC on a 3-month cycle).
  cleaning_interval_months integer not null default 6,

  -- Next Clean Due is STORED and generated by the database, so it can never
  -- drift from Date Cleaned and can be indexed and reported on outside the app.
  -- Never cleaned but purchased: the first clean is due a year after purchase.
  next_clean_due date generated always as (
    case
      when date_cleaned is not null
        then (date_cleaned + make_interval(months => cleaning_interval_months))::date
      when purchase_date is not null
        then (purchase_date + interval '12 months')::date
      else null
    end
  ) stored,

  -- Hardware specification. Which of these apply to which device type is the
  -- app's business (src/lib/specs.js); the database only checks they are sane.
  spec_brand               text,
  spec_model               text,
  spec_processor           text,
  spec_ram                 text,
  spec_storage             text,
  spec_screen_size         text,
  spec_battery_type        text,
  spec_charger_type        text,
  spec_resolution          text,
  spec_hdmi_ports          smallint,
  spec_dp_ports            smallint,

  -- Retirement. Kit at end of life is retired rather than deleted: it leaves
  -- the lists but keeps its record, and an admin can restore it.
  retired_on               date,
  retired_reason           text,
  retired_notes            text,
  retired_by               uuid references auth.users(id) on delete set null,
  retired_by_email         text,
  -- Whether the drive was wiped before it left, and who did it.
  data_wiped               boolean not null default false,
  data_wiped_by            uuid references auth.users(id) on delete set null,
  data_wiped_by_email      text,

  -- Optimistic-concurrency token, bumped by the trigger on every write.
  version                  integer not null default 1,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid references auth.users(id) on delete set null,
  updated_by               uuid references auth.users(id) on delete set null,
  -- Denormalised so the UI can show "last updated by" without reading the
  -- auth schema.
  updated_by_email         text
);

comment on table  public.assets is 'IT hardware assets, their specification and their cleaning history.';
comment on column public.assets.version        is 'Incremented on every write; used for optimistic concurrency control.';
comment on column public.assets.purchase_cost  is 'numeric(12,2), never floating point, so totals do not drift.';
comment on column public.assets.spec_model     is 'Model or variant name, e.g. "Latitude 5540".';

-- Columns for a database created by an older version of this schema. New
-- installs already have them from the CREATE TABLE above; this is how an
-- existing one catches up.
alter table public.assets add column if not exists location          text;
alter table public.assets add column if not exists purchase_cost     numeric(12, 2);
alter table public.assets add column if not exists purchase_date     date;
alter table public.assets add column if not exists spec_brand        text;
alter table public.assets add column if not exists spec_model        text;
alter table public.assets add column if not exists spec_processor    text;
alter table public.assets add column if not exists spec_ram          text;
alter table public.assets add column if not exists spec_storage      text;
alter table public.assets add column if not exists spec_screen_size  text;
alter table public.assets add column if not exists spec_battery_type text;
alter table public.assets add column if not exists spec_charger_type text;
alter table public.assets add column if not exists spec_resolution   text;
alter table public.assets add column if not exists spec_hdmi_ports   smallint;
alter table public.assets add column if not exists spec_dp_ports     smallint;
alter table public.assets add column if not exists retired_on          date;
alter table public.assets add column if not exists retired_reason      text;
alter table public.assets add column if not exists retired_notes       text;
alter table public.assets add column if not exists retired_by          uuid references auth.users(id) on delete set null;
alter table public.assets add column if not exists retired_by_email    text;
alter table public.assets add column if not exists data_wiped          boolean not null default false;
alter table public.assets add column if not exists data_wiped_by       uuid references auth.users(id) on delete set null;
alter table public.assets add column if not exists data_wiped_by_email text;

-- An older database required a user on every asset. It no longer does.
alter table public.assets alter column owner_name drop not null;

-- An older database worked out Next Clean Due from Date Cleaned alone. A
-- generated column cannot be edited in place, so it is dropped and re-added
-- with the current rule. Nothing is lost: every value is recalculated from
-- date_cleaned and purchase_date. The view that reads it is rebuilt in
-- section 7 and the index in section 3.
do $$
declare
  current_rule text;
begin
  select pg_get_expr(d.adbin, d.adrelid) into current_rule
  from pg_attrdef d
  join pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum
  where d.adrelid = 'public.assets'::regclass and a.attname = 'next_clean_due';

  if current_rule is not null and current_rule not like '%purchase_date%' then
    drop view if exists public.assets_with_status;
    alter table public.assets drop column next_clean_due;
    alter table public.assets add column next_clean_due date generated always as (
      case
        when date_cleaned is not null
          then (date_cleaned + make_interval(months => cleaning_interval_months))::date
        when purchase_date is not null
          then (purchase_date + interval '12 months')::date
        else null
      end
    ) stored;
  end if;
end;
$$;

comment on column public.assets.next_clean_due is 'Generated: date_cleaned + cleaning_interval_months, or purchase_date + 12 months if never cleaned. Never written by the client.';


-- =====================================================================
-- 2. Constraints
--    All of them in one place, dropped and re-added so this section is the
--    single answer to "what is allowed in this table".
-- =====================================================================
alter table public.assets drop constraint if exists assets_asset_ref_not_blank;
alter table public.assets add  constraint assets_asset_ref_not_blank
  check (btrim(asset_ref) <> '');

alter table public.assets drop constraint if exists assets_asset_ref_length;
alter table public.assets add  constraint assets_asset_ref_length
  check (char_length(asset_ref) <= 40);

-- NULL means unassigned; a string of spaces is still rejected.
alter table public.assets drop constraint if exists assets_owner_not_blank;
alter table public.assets add  constraint assets_owner_not_blank
  check (owner_name is null or btrim(owner_name) <> '');

alter table public.assets drop constraint if exists assets_department_not_blank;
alter table public.assets add  constraint assets_department_not_blank
  check (btrim(department) <> '');

alter table public.assets drop constraint if exists assets_device_type_valid;
alter table public.assets add  constraint assets_device_type_valid check (
  device_type in (
    'Laptop', 'Desktop', 'Monitor', 'Docking Station',
    'Phone', 'Tablet', 'Printer', 'Peripheral', 'Other'
  )
);

alter table public.assets drop constraint if exists assets_location_valid;
alter table public.assets add  constraint assets_location_valid check (
  location is null or location in ('Remote', 'Hybrid', 'Office', 'Warehouse')
);

alter table public.assets drop constraint if exists assets_purchase_cost_valid;
alter table public.assets add  constraint assets_purchase_cost_valid
  check (purchase_cost is null or purchase_cost >= 0);

alter table public.assets drop constraint if exists assets_cleaned_by_valid;
alter table public.assets add  constraint assets_cleaned_by_valid
  check (cleaned_by is null or cleaned_by in ('AL', 'BB', 'JS', 'RC', 'TM'));

-- "Cleaned By" and "Date Cleaned" only make sense together.
alter table public.assets drop constraint if exists assets_clean_record_complete;
alter table public.assets add  constraint assets_clean_record_complete check (
  (date_cleaned is null and cleaned_by is null)
  or (date_cleaned is not null and cleaned_by is not null)
);

alter table public.assets drop constraint if exists assets_interval_range;
alter table public.assets add  constraint assets_interval_range
  check (cleaning_interval_months between 1 and 60);

alter table public.assets drop constraint if exists assets_notes_length;
alter table public.assets add  constraint assets_notes_length
  check (notes is null or char_length(notes) <= 2000);

-- Specs: blanks are stored as NULL (the trigger below sees to that), and
-- nothing is long enough to break the layout.
alter table public.assets drop constraint if exists assets_spec_text_sane;
alter table public.assets add  constraint assets_spec_text_sane check (
      (spec_brand        is null or (btrim(spec_brand)        <> '' and length(spec_brand)        <= 60))
  and (spec_model        is null or (btrim(spec_model)        <> '' and length(spec_model)        <= 60))
  and (spec_processor    is null or (btrim(spec_processor)    <> '' and length(spec_processor)    <= 60))
  and (spec_ram          is null or (btrim(spec_ram)          <> '' and length(spec_ram)          <= 60))
  and (spec_storage      is null or (btrim(spec_storage)      <> '' and length(spec_storage)      <= 60))
  and (spec_screen_size  is null or (btrim(spec_screen_size)  <> '' and length(spec_screen_size)  <= 60))
  and (spec_battery_type is null or (btrim(spec_battery_type) <> '' and length(spec_battery_type) <= 60))
  and (spec_charger_type is null or (btrim(spec_charger_type) <> '' and length(spec_charger_type) <= 60))
  and (spec_resolution   is null or (btrim(spec_resolution)   <> '' and length(spec_resolution)   <= 60))
);

-- Port counts are small whole numbers; 6 is well beyond any monitor we are
-- likely to buy.
alter table public.assets drop constraint if exists assets_spec_ports_sane;
alter table public.assets add  constraint assets_spec_ports_sane check (
      (spec_hdmi_ports is null or (spec_hdmi_ports between 0 and 6))
  and (spec_dp_ports   is null or (spec_dp_ports   between 0 and 6))
);

-- A retired asset says when and why; an active one carries no retirement
-- details at all, so "is it retired?" has exactly one answer: retired_on.
-- The reasons mirror RETIRE_REASONS in src/lib/constants.js.
alter table public.assets drop constraint if exists assets_retirement_complete;
alter table public.assets add  constraint assets_retirement_complete check (
  (retired_on is null and retired_reason is null and retired_notes is null and not data_wiped)
  -- "is not null" is spelt out: "in (...)" on a null reason is unknown, not
  -- false, and a check lets unknown through.
  or (retired_on is not null and retired_reason is not null and retired_reason in (
        'End of life', 'Beyond repair', 'Replaced', 'Lost', 'Stolen', 'Other'))
);

alter table public.assets drop constraint if exists assets_retired_notes_length;
alter table public.assets add  constraint assets_retired_notes_length
  check (retired_notes is null or char_length(retired_notes) <= 500);

-- "Wiped by" only means something once the wipe is confirmed.
alter table public.assets drop constraint if exists assets_wipe_complete;
alter table public.assets add  constraint assets_wipe_complete check (
  data_wiped or (data_wiped_by is null and data_wiped_by_email is null)
);


-- =====================================================================
-- 3. Indexes
--    Asset Ref is unique case-insensitively and ignoring surrounding
--    whitespace, so "lap-001", "LAP-001 " and "LAP-001" collide.
-- =====================================================================
create unique index if not exists assets_asset_ref_unique_idx
  on public.assets (upper(btrim(asset_ref)));

create index if not exists assets_next_clean_due_idx on public.assets (next_clean_due nulls first);
create index if not exists assets_department_idx     on public.assets (department);
create index if not exists assets_device_type_idx    on public.assets (device_type);
create index if not exists assets_cleaned_by_idx     on public.assets (cleaned_by);
create index if not exists assets_updated_at_idx     on public.assets (updated_at desc);
create index if not exists assets_location_idx       on public.assets (location);
create index if not exists assets_purchase_date_idx  on public.assets (purchase_date);


-- =====================================================================
-- 4. Cleaning status — the single source of truth, in the database
--
--      Not Tracked   -> anything that is not a laptop or desktop
--      Never Cleaned -> no Date Cleaned and no Purchase Date, so no due date
--      Overdue       -> next_clean_due is in the past
--      Due Soon      -> next_clean_due is within the next 30 days
--      OK            -> more than 30 days remaining
--
--    A monitor is tracked for inventory but never joins the cleaning rota,
--    so it must not be counted as "Never Cleaned".
-- =====================================================================
create or replace function public.asset_status(
  p_device_type    text,
  p_date_cleaned   date,
  p_next_clean_due date
)
returns text
language sql
stable
set search_path = public
as $$
  select case
    when p_device_type not in ('Laptop', 'Desktop')         then 'Not Tracked'
    -- A never-cleaned asset with a purchase date is due a year after
    -- purchase, so it is the due date that decides, not the clean.
    when p_next_clean_due is null                           then 'Never Cleaned'
    when p_next_clean_due < current_date                    then 'Overdue'
    when p_next_clean_due <= current_date + 30              then 'Due Soon'
    else 'OK'
  end;
$$;


-- =====================================================================
-- 5. Write trigger: normalisation, validation and audit stamping.
--    Clients cannot forge created_at, updated_by or version.
-- =====================================================================
create or replace function public.handle_asset_write()
returns trigger
language plpgsql
-- security definer so the stamping works regardless of what the signed-in
-- role may touch in the auth schema. The function only ever rewrites the row
-- being written; it never reads or changes another table.
security definer
set search_path = public, auth, pg_temp
as $$
begin
  new.asset_ref  := btrim(new.asset_ref);
  new.owner_name := nullif(btrim(coalesce(new.owner_name, '')), '');
  new.department := btrim(new.department);
  new.notes      := nullif(btrim(coalesce(new.notes, '')), '');

  new.spec_brand        := nullif(btrim(coalesce(new.spec_brand, '')), '');
  new.spec_model        := nullif(btrim(coalesce(new.spec_model, '')), '');
  new.spec_processor    := nullif(btrim(coalesce(new.spec_processor, '')), '');
  new.spec_ram          := nullif(btrim(coalesce(new.spec_ram, '')), '');
  new.spec_storage      := nullif(btrim(coalesce(new.spec_storage, '')), '');
  new.spec_screen_size  := nullif(btrim(coalesce(new.spec_screen_size, '')), '');
  new.spec_battery_type := nullif(btrim(coalesce(new.spec_battery_type, '')), '');
  new.spec_charger_type := nullif(btrim(coalesce(new.spec_charger_type, '')), '');
  new.spec_resolution   := nullif(btrim(coalesce(new.spec_resolution, '')), '');

  if new.date_cleaned is not null and new.date_cleaned > current_date then
    raise exception 'Date Cleaned cannot be in the future (%).', new.date_cleaned
      using errcode = 'check_violation';
  end if;

  -- Retirement. Anyone may retire kit - it is the safe, reversible way out of
  -- the register - but only an admin may bring it back.
  new.retired_notes := nullif(btrim(coalesce(new.retired_notes, '')), '');

  if new.retired_on is not null and new.retired_on > current_date then
    raise exception 'The retirement date cannot be in the future (%).', new.retired_on
      using errcode = 'check_violation';
  end if;

  if tg_op = 'UPDATE' and old.retired_on is not null and new.retired_on is null
     and not public.is_admin() then
    raise exception 'Only an admin can restore retired kit.'
      using errcode = 'insufficient_privilege';
  end if;

  if new.retired_on is null then
    -- Restored, or never retired: no trace of a retirement left behind.
    new.retired_reason      := null;
    new.retired_notes       := null;
    new.retired_by          := null;
    new.retired_by_email    := null;
    new.data_wiped          := false;
    new.data_wiped_by       := null;
    new.data_wiped_by_email := null;
  elsif tg_op = 'INSERT' or old.retired_on is null then
    -- Who retired it is whoever is signed in, whatever the client says.
    new.retired_by       := auth.uid();
    new.retired_by_email := auth.jwt() ->> 'email';
  else
    new.retired_by       := old.retired_by;
    new.retired_by_email := old.retired_by_email;
  end if;

  -- Who wiped it is chosen from the team; the email is looked up rather than
  -- trusted from the client, so it always matches a real account.
  if not new.data_wiped then
    new.data_wiped_by       := null;
    new.data_wiped_by_email := null;
  elsif new.data_wiped_by is not null then
    select u.email into new.data_wiped_by_email from auth.users u where u.id = new.data_wiped_by;
  end if;

  if tg_op = 'INSERT' then
    new.created_at := now();
    new.created_by := auth.uid();
    new.version    := 1;
  else
    -- Preserve creation audit data regardless of what the client sent.
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.version    := old.version + 1;
  end if;

  new.updated_at       := now();
  new.updated_by       := auth.uid();
  new.updated_by_email := coalesce(auth.jwt() ->> 'email', new.updated_by_email);

  return new;
end;
$$;

drop trigger if exists assets_write_trigger on public.assets;
create trigger assets_write_trigger
  before insert or update on public.assets
  for each row execute function public.handle_asset_write();


-- =====================================================================
-- 6. Cleaning history
--    The assets table holds only each asset's MOST RECENT clean: recording
--    a new one overwrites the last. This log keeps every clean, so "how many
--    machines did we clean in September" is answerable at all.
--
--    asset_ref is copied in rather than looked up, so history survives an
--    asset being renamed or retired. Deleting an asset keeps its cleaning
--    record, with asset_id set to null.
-- =====================================================================
create table if not exists public.cleaning_log (
  id              uuid primary key default gen_random_uuid(),
  asset_id        uuid references public.assets(id) on delete set null,
  asset_ref       text not null,
  device_type     text,
  cleaned_on      date not null,
  cleaned_by      text not null,
  logged_at       timestamptz not null default now(),
  logged_by       uuid references auth.users(id),
  logged_by_email text
);

comment on table public.cleaning_log is 'Append-only record of every clean. Written by trigger, never by the app.';

-- Removing an account must not be blocked by the cleans it logged: the log
-- keeps the email, and only the link to the account goes.
alter table public.cleaning_log drop constraint if exists cleaning_log_logged_by_fkey;
alter table public.cleaning_log add  constraint cleaning_log_logged_by_fkey
  foreign key (logged_by) references auth.users(id) on delete set null;

-- One clean per asset per day per person: recording the same clean twice is
-- the same event, and this makes the backfill below safe to re-run.
create unique index if not exists cleaning_log_unique_event
  on public.cleaning_log (asset_id, cleaned_on, cleaned_by);

create index if not exists cleaning_log_cleaned_on_idx on public.cleaning_log (cleaned_on desc);
create index if not exists cleaning_log_asset_ref_idx  on public.cleaning_log (asset_ref);

-- Fires only when the clean itself changes: editing an asset's location or
-- cost must not create a duplicate history entry.
create or replace function public.log_asset_clean()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if new.date_cleaned is null or new.cleaned_by is null then
    return null;
  end if;

  if tg_op = 'UPDATE'
     and new.date_cleaned is not distinct from old.date_cleaned
     and new.cleaned_by   is not distinct from old.cleaned_by then
    return null;
  end if;

  insert into public.cleaning_log
    (asset_id, asset_ref, device_type, cleaned_on, cleaned_by, logged_by, logged_by_email)
  values
    (new.id, new.asset_ref, new.device_type, new.date_cleaned, new.cleaned_by,
     auth.uid(), auth.jwt() ->> 'email')
  on conflict (asset_id, cleaned_on, cleaned_by) do nothing;

  return null;
end;
$$;

drop trigger if exists assets_log_clean on public.assets;
create trigger assets_log_clean
  after insert or update on public.assets
  for each row execute function public.log_asset_clean();

-- Seed the log from whatever the register already holds, so it is not empty
-- on day one. On a new database this finds nothing and does nothing.
insert into public.cleaning_log (asset_id, asset_ref, device_type, cleaned_on, cleaned_by)
select a.id, a.asset_ref, a.device_type, a.date_cleaned, a.cleaned_by
from public.assets a
where a.date_cleaned is not null and a.cleaned_by is not null
on conflict (asset_id, cleaned_on, cleaned_by) do nothing;


-- =====================================================================
-- 6b. Asset history
--     Who has had each asset, and where it has been. One row per change to
--     the user, department, location, device type or reference, written by
--     trigger so it records every change however it was made - one edit, or
--     a bulk reassignment. Cleans are not repeated here: the timeline reads
--     them from cleaning_log.
--
--     History starts the day this section first runs. Assets that already
--     exist get one "tracking_started" row recording who had them then.
-- =====================================================================
create table if not exists public.asset_events (
  id           uuid primary key default gen_random_uuid(),
  asset_id     uuid references public.assets(id) on delete set null,
  asset_ref    text not null,
  event_type   text not null,
  old_value    text,
  new_value    text,
  -- For created / tracking_started: who, where and which department then.
  details      jsonb,
  happened_at  timestamptz not null default now(),
  actor_id     uuid references auth.users(id) on delete set null,
  actor_email  text
);

comment on table public.asset_events is 'Append-only change history per asset. Written by trigger, never by the app.';

alter table public.asset_events drop constraint if exists asset_events_type_valid;
alter table public.asset_events add  constraint asset_events_type_valid check (
  event_type in ('created', 'tracking_started', 'owner', 'department', 'location', 'device_type', 'asset_ref',
                 'retired', 'restored')
);

create index if not exists asset_events_asset_idx on public.asset_events (asset_id, happened_at);

create or replace function public.log_asset_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  who_id    uuid := auth.uid();
  who_email text := auth.jwt() ->> 'email';
begin
  if tg_op = 'INSERT' then
    insert into public.asset_events (asset_id, asset_ref, event_type, details, actor_id, actor_email)
    values (new.id, new.asset_ref, 'created',
            jsonb_build_object('owner', new.owner_name, 'department', new.department, 'location', new.location),
            who_id, who_email);
    return null;
  end if;

  if new.owner_name is distinct from old.owner_name then
    insert into public.asset_events (asset_id, asset_ref, event_type, old_value, new_value, actor_id, actor_email)
    values (new.id, new.asset_ref, 'owner', old.owner_name, new.owner_name, who_id, who_email);
  end if;
  if new.department is distinct from old.department then
    insert into public.asset_events (asset_id, asset_ref, event_type, old_value, new_value, actor_id, actor_email)
    values (new.id, new.asset_ref, 'department', old.department, new.department, who_id, who_email);
  end if;
  if new.location is distinct from old.location then
    insert into public.asset_events (asset_id, asset_ref, event_type, old_value, new_value, actor_id, actor_email)
    values (new.id, new.asset_ref, 'location', old.location, new.location, who_id, who_email);
  end if;
  if new.device_type is distinct from old.device_type then
    insert into public.asset_events (asset_id, asset_ref, event_type, old_value, new_value, actor_id, actor_email)
    values (new.id, new.asset_ref, 'device_type', old.device_type, new.device_type, who_id, who_email);
  end if;
  if new.asset_ref is distinct from old.asset_ref then
    insert into public.asset_events (asset_id, asset_ref, event_type, old_value, new_value, actor_id, actor_email)
    values (new.id, new.asset_ref, 'asset_ref', old.asset_ref, new.asset_ref, who_id, who_email);
  end if;
  if old.retired_on is null and new.retired_on is not null then
    insert into public.asset_events (asset_id, asset_ref, event_type, details, actor_id, actor_email)
    values (new.id, new.asset_ref, 'retired',
            jsonb_build_object('retired_on', new.retired_on, 'reason', new.retired_reason,
                               'notes', new.retired_notes, 'data_wiped', new.data_wiped,
                               'data_wiped_by', new.data_wiped_by_email),
            who_id, who_email);
  end if;
  if old.retired_on is not null and new.retired_on is null then
    insert into public.asset_events (asset_id, asset_ref, event_type, actor_id, actor_email)
    values (new.id, new.asset_ref, 'restored', who_id, who_email);
  end if;

  return null;
end;
$$;

drop trigger if exists assets_log_change on public.assets;
create trigger assets_log_change
  after insert or update on public.assets
  for each row execute function public.log_asset_change();

-- A starting point for assets that predate the history: who has them now.
-- Re-running finds every asset already has a row and adds nothing.
insert into public.asset_events (asset_id, asset_ref, event_type, details, happened_at)
select a.id, a.asset_ref, 'tracking_started',
       jsonb_build_object('owner', a.owner_name, 'department', a.department, 'location', a.location),
       now()
from public.assets a
where not exists (select 1 from public.asset_events e where e.asset_id = a.id);


-- =====================================================================
-- 7. The read-only view the app queries
--    It selects a.*, which freezes the column list at creation time, so it
--    has to be dropped and recreated rather than replaced. Dropping a view
--    also drops its grants, which is why the grants come afterwards.
-- =====================================================================
drop view if exists public.assets_with_status;

create view public.assets_with_status
with (security_invoker = on) as
select
  a.*,
  case
    when a.retired_on is not null then 'Retired'
    else public.asset_status(a.device_type, a.date_cleaned, a.next_clean_due)
  end                                                                  as status,
  (a.next_clean_due - current_date)                                    as days_until_due
from public.assets a;

comment on view public.assets_with_status is 'assets + derived status/days_until_due. Read-only surface for the app.';


-- =====================================================================
-- 8. Row Level Security
--    Every signed-in member of the IT team shares one dataset. Anonymous
--    visitors get nothing at all, which is what makes it safe to ship the
--    anon key in the browser bundle.
-- =====================================================================
alter table public.assets       enable row level security;
alter table public.cleaning_log enable row level security;
alter table public.asset_events enable row level security;

drop policy if exists "assets_select_authenticated" on public.assets;
create policy "assets_select_authenticated"
  on public.assets for select
  to authenticated
  using (true);

drop policy if exists "assets_insert_authenticated" on public.assets;
create policy "assets_insert_authenticated"
  on public.assets for insert
  to authenticated
  with check (true);

drop policy if exists "assets_update_authenticated" on public.assets;
create policy "assets_update_authenticated"
  on public.assets for update
  to authenticated
  using (true)
  with check (true);

-- Deleting is for admins only, and its policy is in section 10 because it
-- needs is_admin(). This removes the older everyone-can-delete policy.
drop policy if exists "assets_delete_authenticated" on public.assets;

-- History is readable by everyone signed in and written only by the trigger
-- above, which runs as its owner. Nobody edits or deletes history through the
-- app - that is the point of a log.
drop policy if exists "cleaning_log_select_authenticated" on public.cleaning_log;
create policy "cleaning_log_select_authenticated"
  on public.cleaning_log for select
  to authenticated
  using (true);

drop policy if exists "asset_events_select_authenticated" on public.asset_events;
create policy "asset_events_select_authenticated"
  on public.asset_events for select
  to authenticated
  using (true);

revoke all on public.assets             from anon;
revoke all on public.asset_events       from anon;
revoke all on public.assets_with_status from anon;
revoke all on public.cleaning_log       from anon;

grant select, insert, update, delete on public.assets              to authenticated;
grant select                         on public.assets_with_status  to authenticated;
grant select                         on public.cleaning_log        to authenticated;
grant select                         on public.asset_events        to authenticated;
grant execute on function public.asset_status(text, date, date)    to authenticated;


-- =====================================================================
-- 9. Realtime: push changes to every open browser tab, so two people
--    editing at once see each other's work without refreshing.
-- =====================================================================
do $$
begin
  alter publication supabase_realtime add table public.assets;
exception
  when duplicate_object then null;
  when undefined_object then null;  -- publication missing (self-hosted); ignore
end;
$$;

-- Realtime also needs the old row to identify deletes under RLS.
alter table public.assets replica identity full;


-- =====================================================================
-- 10. Admins and users
--     Every account is either an admin or a user. Both can add, edit, clean,
--     repair and retire assets; only admins can delete an asset, restore
--     retired kit, and add, remove and manage accounts from the Admin page. Creating an account needs Supabase's service-role key,
--     which must never reach a browser, so the Admin page talks to the
--     admin-users Edge Function (supabase/functions/admin-users), and that
--     checks this table before doing anything.
--
--     No account without a row here is an admin. The app reads its own row
--     to decide whether to show the Admin page; it cannot write any row.
-- =====================================================================
create table if not exists public.user_roles (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  role       text not null default 'user',
  created_at timestamptz not null default now()
);

alter table public.user_roles drop constraint if exists user_roles_role_valid;
alter table public.user_roles add  constraint user_roles_role_valid check (role in ('admin', 'user'));

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'
  );
$$;

alter table public.user_roles enable row level security;

drop policy if exists "user_roles_select_own_or_admin" on public.user_roles;
create policy "user_roles_select_own_or_admin"
  on public.user_roles for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());

revoke all on public.user_roles from anon, authenticated;
grant select on public.user_roles to authenticated;
grant execute on function public.is_admin() to authenticated;

-- Only admins delete assets. Everyone else retires kit instead, which keeps
-- the record and can be undone; a delete cannot. A delete by anyone else
-- simply matches no rows.
drop policy if exists "assets_delete_admin" on public.assets;
create policy "assets_delete_admin"
  on public.assets for delete
  to authenticated
  using (public.is_admin());

-- Somebody has to be the first admin. If there is none yet, it is the
-- oldest account - in practice whoever set the project up. To choose a
-- different one, run:
--   insert into public.user_roles (user_id, role)
--   select id, 'admin' from auth.users where email = 'you@example.com'
--   on conflict (user_id) do update set role = 'admin';
insert into public.user_roles (user_id, role)
select u.id, 'admin'
from auth.users u
where not exists (select 1 from public.user_roles where role = 'admin')
order by u.created_at
limit 1
on conflict (user_id) do update set role = 'admin';


-- =====================================================================
-- 11. Repairs
--     In-house fixes: what was wrong, who fixed it, when, and each part
--     replaced with its cost. The parts are one list on the repair, so a
--     repair and its parts are saved together or not at all, and the total
--     is worked out here rather than trusted from the browser.
-- =====================================================================
create table if not exists public.repairs (
  id               uuid primary key default gen_random_uuid(),
  asset_id         uuid not null references public.assets(id) on delete cascade,
  repaired_on      date not null,
  fault            text not null,
  -- [{"part": "Battery", "cost": 45.00}, ...]
  parts            jsonb not null default '[]'::jsonb,
  total_cost       numeric(12, 2) not null default 0,
  fixed_by         uuid references auth.users(id) on delete set null,
  fixed_by_email   text,
  notes            text,
  created_at       timestamptz not null default now(),
  created_by       uuid references auth.users(id) on delete set null,
  created_by_email text,
  updated_at       timestamptz not null default now(),
  updated_by_email text
);

comment on table public.repairs is 'In-house repairs per asset, with itemised parts. Deleting is for admins.';

alter table public.repairs drop constraint if exists repairs_fault_valid;
alter table public.repairs add  constraint repairs_fault_valid
  check (btrim(fault) <> '' and char_length(fault) <= 500);

alter table public.repairs drop constraint if exists repairs_notes_length;
alter table public.repairs add  constraint repairs_notes_length
  check (notes is null or char_length(notes) <= 2000);

alter table public.repairs drop constraint if exists repairs_parts_is_list;
alter table public.repairs add  constraint repairs_parts_is_list
  check (jsonb_typeof(parts) = 'array');

alter table public.repairs drop constraint if exists repairs_total_valid;
alter table public.repairs add  constraint repairs_total_valid check (total_cost >= 0);

create index if not exists repairs_asset_idx on public.repairs (asset_id, repaired_on desc);
create index if not exists repairs_date_idx  on public.repairs (repaired_on desc);

create or replace function public.handle_repair_write()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  part      jsonb;
  total     numeric(12, 2) := 0;
  fixer     text;
begin
  new.fault := btrim(coalesce(new.fault, ''));
  new.notes := nullif(btrim(coalesce(new.notes, '')), '');

  if new.repaired_on > current_date then
    raise exception 'The repair date cannot be in the future (%).', new.repaired_on
      using errcode = 'check_violation';
  end if;

  -- Every part needs a name and a cost; the total is their sum.
  if jsonb_typeof(new.parts) <> 'array' then
    raise exception 'Parts must be a list.' using errcode = 'check_violation';
  end if;
  if jsonb_array_length(new.parts) > 30 then
    raise exception 'A repair can list at most 30 parts.' using errcode = 'check_violation';
  end if;
  for part in select value from jsonb_array_elements(new.parts) loop
    if jsonb_typeof(part) <> 'object'
       or jsonb_typeof(part -> 'part') is distinct from 'string'
       or btrim(part ->> 'part') = ''
       or char_length(part ->> 'part') > 80
       or jsonb_typeof(part -> 'cost') is distinct from 'number'
       or (part ->> 'cost')::numeric < 0
       or (part ->> 'cost')::numeric > 100000 then
      raise exception 'Each part needs a name and a cost between £0 and £100,000.'
        using errcode = 'check_violation';
    end if;
    total := total + round((part ->> 'cost')::numeric, 2);
  end loop;

  -- Stored tidily: trimmed names, costs to the penny, nothing else.
  new.parts := coalesce(
    (select jsonb_agg(jsonb_build_object('part', btrim(t.p ->> 'part'),
                                         'cost', round((t.p ->> 'cost')::numeric, 2))
                      order by t.ord)
     from jsonb_array_elements(new.parts) with ordinality as t(p, ord)),
    '[]'::jsonb);
  new.total_cost := total;

  -- Who fixed it: chosen from the team, defaulting to whoever logs it. The
  -- email is looked up, never trusted from the browser.
  if tg_op = 'INSERT' and new.fixed_by is null then
    new.fixed_by := auth.uid();
  end if;
  if new.fixed_by is not null then
    select u.email into fixer from auth.users u where u.id = new.fixed_by;
    if fixer is null then
      raise exception 'Choose who fixed it from the team.' using errcode = 'check_violation';
    end if;
    new.fixed_by_email := fixer;
  elsif tg_op = 'UPDATE' then
    -- Their account has since been removed; keep the name on the record.
    new.fixed_by_email := old.fixed_by_email;
  end if;

  if tg_op = 'INSERT' then
    new.created_at       := now();
    new.created_by       := auth.uid();
    new.created_by_email := auth.jwt() ->> 'email';
  else
    -- A repair belongs to one asset for good, and its creation is history.
    new.asset_id         := old.asset_id;
    new.created_at       := old.created_at;
    new.created_by       := old.created_by;
    new.created_by_email := old.created_by_email;
  end if;
  new.updated_at       := now();
  new.updated_by_email := auth.jwt() ->> 'email';

  return new;
end;
$$;

drop trigger if exists repairs_write_trigger on public.repairs;
create trigger repairs_write_trigger
  before insert or update on public.repairs
  for each row execute function public.handle_repair_write();

alter table public.repairs enable row level security;

drop policy if exists "repairs_select_authenticated" on public.repairs;
create policy "repairs_select_authenticated"
  on public.repairs for select to authenticated using (true);

drop policy if exists "repairs_insert_authenticated" on public.repairs;
create policy "repairs_insert_authenticated"
  on public.repairs for insert to authenticated with check (true);

drop policy if exists "repairs_update_authenticated" on public.repairs;
create policy "repairs_update_authenticated"
  on public.repairs for update to authenticated using (true) with check (true);

drop policy if exists "repairs_delete_admin" on public.repairs;
create policy "repairs_delete_admin"
  on public.repairs for delete to authenticated using (public.is_admin());

revoke all on public.repairs from anon;
grant select, insert, update, delete on public.repairs to authenticated;


-- =====================================================================
-- 12. Attachments: invoices, receipts and photos
--     The files live in a PRIVATE Storage bucket - nobody can open one
--     without being signed in, even with its address - and this table
--     records what each file is and what it belongs to: an asset, and
--     optionally one of its repairs.
--
--     Files are kept under the asset's own folder (<asset id>/...), so a
--     row can only ever point at a file belonging to its own asset.
--     Anyone signed in can add files; the person who added one, or an
--     admin, can remove it. Uses the Supabase Free plan's 1 GB of storage.
-- =====================================================================
create table if not exists public.attachments (
  id                uuid primary key default gen_random_uuid(),
  asset_id          uuid not null references public.assets(id) on delete cascade,
  repair_id         uuid references public.repairs(id) on delete cascade,
  storage_path      text not null,
  file_name         text not null,
  content_type      text not null,
  size_bytes        integer not null,
  uploaded_at       timestamptz not null default now(),
  uploaded_by       uuid references auth.users(id) on delete set null,
  uploaded_by_email text
);

comment on table public.attachments is 'Files attached to an asset or one of its repairs. The files themselves are in the asset-files bucket.';

create unique index if not exists attachments_path_unique on public.attachments (storage_path);
create index if not exists attachments_asset_idx  on public.attachments (asset_id, uploaded_at);
create index if not exists attachments_repair_idx on public.attachments (repair_id);

-- The types and the 10 MB limit mirror the bucket below and
-- ATTACHMENT_TYPES in src/lib/attachments.js.
alter table public.attachments drop constraint if exists attachments_file_valid;
alter table public.attachments add  constraint attachments_file_valid check (
      size_bytes between 1 and 10485760
  and content_type in ('image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf')
  and char_length(btrim(file_name)) between 1 and 200
  and storage_path like (asset_id::text || '/%')
);

create or replace function public.handle_attachment_write()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if new.repair_id is not null and not exists (
    select 1 from public.repairs r where r.id = new.repair_id and r.asset_id = new.asset_id
  ) then
    raise exception 'That repair belongs to a different asset.' using errcode = 'check_violation';
  end if;

  new.file_name         := btrim(new.file_name);
  new.uploaded_at       := now();
  new.uploaded_by       := auth.uid();
  new.uploaded_by_email := auth.jwt() ->> 'email';
  return new;
end;
$$;

drop trigger if exists attachments_write_trigger on public.attachments;
create trigger attachments_write_trigger
  before insert on public.attachments
  for each row execute function public.handle_attachment_write();

alter table public.attachments enable row level security;

drop policy if exists "attachments_select_authenticated" on public.attachments;
create policy "attachments_select_authenticated"
  on public.attachments for select to authenticated using (true);

drop policy if exists "attachments_insert_authenticated" on public.attachments;
create policy "attachments_insert_authenticated"
  on public.attachments for insert to authenticated with check (true);

drop policy if exists "attachments_delete_own_or_admin" on public.attachments;
create policy "attachments_delete_own_or_admin"
  on public.attachments for delete to authenticated
  using (uploaded_by = auth.uid() or public.is_admin());

-- No update: a file is replaced by removing it and adding the new one.
revoke all on public.attachments from anon;
grant select, insert, delete on public.attachments to authenticated;

-- The bucket. Private: files are opened through short-lived signed links.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('asset-files', 'asset-files', false, 10485760,
        array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf'])
on conflict (id) do update
  set public             = false,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "asset_files_read" on storage.objects;
create policy "asset_files_read"
  on storage.objects for select to authenticated
  using (bucket_id = 'asset-files');

drop policy if exists "asset_files_upload" on storage.objects;
create policy "asset_files_upload"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'asset-files');

-- Removing a file: whoever added it, or an admin. A file with no record
-- (an upload whose record never got saved) may be tidied up by anyone.
drop policy if exists "asset_files_delete" on storage.objects;
create policy "asset_files_delete"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'asset-files' and (
      public.is_admin()
      or exists (select 1 from public.attachments a
                 where a.storage_path = objects.name and a.uploaded_by = auth.uid())
      or not exists (select 1 from public.attachments a where a.storage_path = objects.name)
    )
  );


-- =====================================================================
-- 13. The team, for "who fixed it" and "who wiped it"
--     Signed-in people may see who else has an account - just the id and
--     email - so those choices can offer the whole team. Anonymous
--     visitors get nothing.
-- =====================================================================
create or replace function public.team_members()
returns table (id uuid, email text)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select u.id, u.email::text
  from auth.users u
  where auth.uid() is not null
    and u.email is not null
    and u.deleted_at is null
  order by u.email;
$$;

revoke all on function public.team_members() from public, anon;
grant execute on function public.team_members() to authenticated;


-- =====================================================================
-- Done. Check it worked:
--
--   select count(*) from public.assets;
--   select status, count(*) from public.assets_with_status group by status order by 1;
--   select cleaned_on, asset_ref, cleaned_by from public.cleaning_log
--     order by cleaned_on desc limit 10;
--
-- Then turn off public sign-ups under Authentication -> Providers -> Email.
-- Accounts are added from the app's Admin page once the admin-users Edge
-- Function is deployed (see README), or by hand under Authentication ->
-- Users (tick "Auto Confirm User").
-- =====================================================================
