-- =====================================================================
-- IT Hardware Maintenance Tracker — complete database setup
--
-- ONE script that builds the whole database: tables, generated columns,
-- constraints, indexes, status logic, audit triggers, the cleaning history
-- log, Row Level Security and Realtime.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste all of this ->
--   Run. It should finish with "Success. No rows returned".
--
-- WHEN TO USE IT
--   * A brand-new Supabase project: this is the only script you need. The
--     numbered migration files next to it are the history of how an older
--     database reached this same state; a new one does not need them.
--   * An existing database that has already had schema.sql and migrations
--     001-004 applied: running this changes nothing. It is written to be
--     safe either way.
--
-- IT NEVER DESTROYS DATA. Nothing here drops a table or deletes a row. The
-- only things dropped are the read-only view, policies, triggers and
-- constraints, each recreated immediately afterwards.
--
-- Reference lists (device types, locations, cleaners) are CHECK constraints
-- rather than lookup tables, so a small team can see the whole list at a
-- glance. To change one, edit the constraint here AND src/lib/constants.js.
-- =====================================================================

create extension if not exists pgcrypto;


-- =====================================================================
-- 1. The assets table
-- =====================================================================
create table if not exists public.assets (
  id                       uuid primary key default gen_random_uuid(),

  asset_ref                text not null,
  device_type              text not null,
  -- Nullable on purpose: an asset nobody holds is "unassigned", and blank is
  -- stored as NULL so there is exactly one way to represent "nobody has this".
  owner_name               text,
  department               text not null,

  location                 text,
  purchase_cost            numeric(12, 2),
  purchase_date            date,

  date_cleaned             date,
  cleaned_by               text,
  notes                    text,

  -- Cleaning cadence. Defaults to the 6-month business rule but can be
  -- overridden per asset (e.g. a dusty workshop PC on a 3-month cycle).
  cleaning_interval_months integer not null default 6,

  -- Next Clean Due is STORED and generated by the database, so it can never
  -- drift from Date Cleaned and can be indexed and reported on outside the app.
  next_clean_due date generated always as (
    case
      when date_cleaned is null then null
      else (date_cleaned + make_interval(months => cleaning_interval_months))::date
    end
  ) stored,

  -- Hardware specification. Which of these apply to which device type is the
  -- app's business (src/lib/specs.js); the database only checks they are sane.
  spec_brand               text,
  spec_model               text,
  spec_processor           text,
  spec_ram                 text,
  spec_storage             text,
  spec_screen_size         text,
  spec_battery_type        text,
  spec_charger_type        text,
  spec_resolution          text,
  spec_hdmi_ports          smallint,
  spec_dp_ports            smallint,

  -- Optimistic-concurrency token, bumped by the trigger on every write.
  version                  integer not null default 1,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid references auth.users(id) on delete set null,
  updated_by               uuid references auth.users(id) on delete set null,
  -- Denormalised so the UI can show "last updated by" without reading the
  -- auth schema.
  updated_by_email         text
);

comment on table  public.assets is 'IT hardware assets, their specification and their cleaning history.';
comment on column public.assets.next_clean_due is 'Generated: date_cleaned + cleaning_interval_months. Never written by the client.';
comment on column public.assets.version        is 'Incremented on every write; used for optimistic concurrency control.';
comment on column public.assets.purchase_cost  is 'numeric(12,2), never floating point, so totals do not drift.';
comment on column public.assets.spec_model     is 'Model or variant name, e.g. "Latitude 5540".';

-- Columns for a database created by an older version of this schema. New
-- installs already have them from the CREATE TABLE above; this is how an
-- existing one catches up.
alter table public.assets add column if not exists location          text;
alter table public.assets add column if not exists purchase_cost     numeric(12, 2);
alter table public.assets add column if not exists purchase_date     date;
alter table public.assets add column if not exists spec_brand        text;
alter table public.assets add column if not exists spec_model        text;
alter table public.assets add column if not exists spec_processor    text;
alter table public.assets add column if not exists spec_ram          text;
alter table public.assets add column if not exists spec_storage      text;
alter table public.assets add column if not exists spec_screen_size  text;
alter table public.assets add column if not exists spec_battery_type text;
alter table public.assets add column if not exists spec_charger_type text;
alter table public.assets add column if not exists spec_resolution   text;
alter table public.assets add column if not exists spec_hdmi_ports   smallint;
alter table public.assets add column if not exists spec_dp_ports     smallint;

-- An older database required a user on every asset. It no longer does.
alter table public.assets alter column owner_name drop not null;


-- =====================================================================
-- 2. Constraints
--    All of them in one place, dropped and re-added so this section is the
--    single answer to "what is allowed in this table".
-- =====================================================================
alter table public.assets drop constraint if exists assets_asset_ref_not_blank;
alter table public.assets add  constraint assets_asset_ref_not_blank
  check (btrim(asset_ref) <> '');

alter table public.assets drop constraint if exists assets_asset_ref_length;
alter table public.assets add  constraint assets_asset_ref_length
  check (char_length(asset_ref) <= 40);

-- NULL means unassigned; a string of spaces is still rejected.
alter table public.assets drop constraint if exists assets_owner_not_blank;
alter table public.assets add  constraint assets_owner_not_blank
  check (owner_name is null or btrim(owner_name) <> '');

alter table public.assets drop constraint if exists assets_department_not_blank;
alter table public.assets add  constraint assets_department_not_blank
  check (btrim(department) <> '');

alter table public.assets drop constraint if exists assets_device_type_valid;
alter table public.assets add  constraint assets_device_type_valid check (
  device_type in (
    'Laptop', 'Desktop', 'Monitor', 'Docking Station',
    'Phone', 'Tablet', 'Printer', 'Peripheral', 'Other'
  )
);

alter table public.assets drop constraint if exists assets_location_valid;
alter table public.assets add  constraint assets_location_valid check (
  location is null or location in ('Remote', 'Hybrid', 'Office', 'Warehouse')
);

alter table public.assets drop constraint if exists assets_purchase_cost_valid;
alter table public.assets add  constraint assets_purchase_cost_valid
  check (purchase_cost is null or purchase_cost >= 0);

alter table public.assets drop constraint if exists assets_cleaned_by_valid;
alter table public.assets add  constraint assets_cleaned_by_valid
  check (cleaned_by is null or cleaned_by in ('AL', 'BB', 'JS', 'RC', 'TM'));

-- "Cleaned By" and "Date Cleaned" only make sense together.
alter table public.assets drop constraint if exists assets_clean_record_complete;
alter table public.assets add  constraint assets_clean_record_complete check (
  (date_cleaned is null and cleaned_by is null)
  or (date_cleaned is not null and cleaned_by is not null)
);

alter table public.assets drop constraint if exists assets_interval_range;
alter table public.assets add  constraint assets_interval_range
  check (cleaning_interval_months between 1 and 60);

alter table public.assets drop constraint if exists assets_notes_length;
alter table public.assets add  constraint assets_notes_length
  check (notes is null or char_length(notes) <= 2000);

-- Specs: blanks are stored as NULL (the trigger below sees to that), and
-- nothing is long enough to break the layout.
alter table public.assets drop constraint if exists assets_spec_text_sane;
alter table public.assets add  constraint assets_spec_text_sane check (
      (spec_brand        is null or (btrim(spec_brand)        <> '' and length(spec_brand)        <= 60))
  and (spec_model        is null or (btrim(spec_model)        <> '' and length(spec_model)        <= 60))
  and (spec_processor    is null or (btrim(spec_processor)    <> '' and length(spec_processor)    <= 60))
  and (spec_ram          is null or (btrim(spec_ram)          <> '' and length(spec_ram)          <= 60))
  and (spec_storage      is null or (btrim(spec_storage)      <> '' and length(spec_storage)      <= 60))
  and (spec_screen_size  is null or (btrim(spec_screen_size)  <> '' and length(spec_screen_size)  <= 60))
  and (spec_battery_type is null or (btrim(spec_battery_type) <> '' and length(spec_battery_type) <= 60))
  and (spec_charger_type is null or (btrim(spec_charger_type) <> '' and length(spec_charger_type) <= 60))
  and (spec_resolution   is null or (btrim(spec_resolution)   <> '' and length(spec_resolution)   <= 60))
);

-- Port counts are small whole numbers; 6 is well beyond any monitor we are
-- likely to buy.
alter table public.assets drop constraint if exists assets_spec_ports_sane;
alter table public.assets add  constraint assets_spec_ports_sane check (
      (spec_hdmi_ports is null or (spec_hdmi_ports between 0 and 6))
  and (spec_dp_ports   is null or (spec_dp_ports   between 0 and 6))
);


-- =====================================================================
-- 3. Indexes
--    Asset Ref is unique case-insensitively and ignoring surrounding
--    whitespace, so "lap-001", "LAP-001 " and "LAP-001" collide.
-- =====================================================================
create unique index if not exists assets_asset_ref_unique_idx
  on public.assets (upper(btrim(asset_ref)));

create index if not exists assets_next_clean_due_idx on public.assets (next_clean_due nulls first);
create index if not exists assets_department_idx     on public.assets (department);
create index if not exists assets_device_type_idx    on public.assets (device_type);
create index if not exists assets_cleaned_by_idx     on public.assets (cleaned_by);
create index if not exists assets_updated_at_idx     on public.assets (updated_at desc);
create index if not exists assets_location_idx       on public.assets (location);
create index if not exists assets_purchase_date_idx  on public.assets (purchase_date);


-- =====================================================================
-- 4. Cleaning status — the single source of truth, in the database
--
--      Not Tracked   -> anything that is not a laptop or desktop
--      Never Cleaned -> no Date Cleaned recorded
--      Overdue       -> next_clean_due is in the past
--      Due Soon      -> next_clean_due is within the next 30 days
--      OK            -> more than 30 days remaining
--
--    A monitor is tracked for inventory but never joins the cleaning rota,
--    so it must not be counted as "Never Cleaned".
-- =====================================================================
create or replace function public.asset_status(
  p_device_type    text,
  p_date_cleaned   date,
  p_next_clean_due date
)
returns text
language sql
stable
set search_path = public
as $$
  select case
    when p_device_type not in ('Laptop', 'Desktop')         then 'Not Tracked'
    when p_date_cleaned is null or p_next_clean_due is null then 'Never Cleaned'
    when p_next_clean_due < current_date                    then 'Overdue'
    when p_next_clean_due <= current_date + 30              then 'Due Soon'
    else 'OK'
  end;
$$;


-- =====================================================================
-- 5. Write trigger: normalisation, validation and audit stamping.
--    Clients cannot forge created_at, updated_by or version.
-- =====================================================================
create or replace function public.handle_asset_write()
returns trigger
language plpgsql
-- security definer so the stamping works regardless of what the signed-in
-- role may touch in the auth schema. The function only ever rewrites the row
-- being written; it never reads or changes another table.
security definer
set search_path = public, auth, pg_temp
as $$
begin
  new.asset_ref  := btrim(new.asset_ref);
  new.owner_name := nullif(btrim(coalesce(new.owner_name, '')), '');
  new.department := btrim(new.department);
  new.notes      := nullif(btrim(coalesce(new.notes, '')), '');

  new.spec_brand        := nullif(btrim(coalesce(new.spec_brand, '')), '');
  new.spec_model        := nullif(btrim(coalesce(new.spec_model, '')), '');
  new.spec_processor    := nullif(btrim(coalesce(new.spec_processor, '')), '');
  new.spec_ram          := nullif(btrim(coalesce(new.spec_ram, '')), '');
  new.spec_storage      := nullif(btrim(coalesce(new.spec_storage, '')), '');
  new.spec_screen_size  := nullif(btrim(coalesce(new.spec_screen_size, '')), '');
  new.spec_battery_type := nullif(btrim(coalesce(new.spec_battery_type, '')), '');
  new.spec_charger_type := nullif(btrim(coalesce(new.spec_charger_type, '')), '');
  new.spec_resolution   := nullif(btrim(coalesce(new.spec_resolution, '')), '');

  if new.date_cleaned is not null and new.date_cleaned > current_date then
    raise exception 'Date Cleaned cannot be in the future (%).', new.date_cleaned
      using errcode = 'check_violation';
  end if;

  if tg_op = 'INSERT' then
    new.created_at := now();
    new.created_by := auth.uid();
    new.version    := 1;
  else
    -- Preserve creation audit data regardless of what the client sent.
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.version    := old.version + 1;
  end if;

  new.updated_at       := now();
  new.updated_by       := auth.uid();
  new.updated_by_email := coalesce(auth.jwt() ->> 'email', new.updated_by_email);

  return new;
end;
$$;

drop trigger if exists assets_write_trigger on public.assets;
create trigger assets_write_trigger
  before insert or update on public.assets
  for each row execute function public.handle_asset_write();


-- =====================================================================
-- 6. Cleaning history
--    The assets table holds only each asset's MOST RECENT clean: recording
--    a new one overwrites the last. This log keeps every clean, so "how many
--    machines did we clean in September" is answerable at all.
--
--    asset_ref is copied in rather than looked up, so history survives an
--    asset being renamed or retired. Deleting an asset keeps its cleaning
--    record, with asset_id set to null.
-- =====================================================================
create table if not exists public.cleaning_log (
  id              uuid primary key default gen_random_uuid(),
  asset_id        uuid references public.assets(id) on delete set null,
  asset_ref       text not null,
  device_type     text,
  cleaned_on      date not null,
  cleaned_by      text not null,
  logged_at       timestamptz not null default now(),
  logged_by       uuid references auth.users(id),
  logged_by_email text
);

comment on table public.cleaning_log is 'Append-only record of every clean. Written by trigger, never by the app.';

-- One clean per asset per day per person: recording the same clean twice is
-- the same event, and this makes the backfill below safe to re-run.
create unique index if not exists cleaning_log_unique_event
  on public.cleaning_log (asset_id, cleaned_on, cleaned_by);

create index if not exists cleaning_log_cleaned_on_idx on public.cleaning_log (cleaned_on desc);
create index if not exists cleaning_log_asset_ref_idx  on public.cleaning_log (asset_ref);

-- Fires only when the clean itself changes: editing an asset's location or
-- cost must not create a duplicate history entry.
create or replace function public.log_asset_clean()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if new.date_cleaned is null or new.cleaned_by is null then
    return null;
  end if;

  if tg_op = 'UPDATE'
     and new.date_cleaned is not distinct from old.date_cleaned
     and new.cleaned_by   is not distinct from old.cleaned_by then
    return null;
  end if;

  insert into public.cleaning_log
    (asset_id, asset_ref, device_type, cleaned_on, cleaned_by, logged_by, logged_by_email)
  values
    (new.id, new.asset_ref, new.device_type, new.date_cleaned, new.cleaned_by,
     auth.uid(), auth.jwt() ->> 'email')
  on conflict (asset_id, cleaned_on, cleaned_by) do nothing;

  return null;
end;
$$;

drop trigger if exists assets_log_clean on public.assets;
create trigger assets_log_clean
  after insert or update on public.assets
  for each row execute function public.log_asset_clean();

-- Seed the log from whatever the register already holds, so it is not empty
-- on day one. On a new database this finds nothing and does nothing.
insert into public.cleaning_log (asset_id, asset_ref, device_type, cleaned_on, cleaned_by)
select a.id, a.asset_ref, a.device_type, a.date_cleaned, a.cleaned_by
from public.assets a
where a.date_cleaned is not null and a.cleaned_by is not null
on conflict (asset_id, cleaned_on, cleaned_by) do nothing;


-- =====================================================================
-- 7. The read-only view the app queries
--    It selects a.*, which freezes the column list at creation time, so it
--    has to be dropped and recreated rather than replaced. Dropping a view
--    also drops its grants, which is why the grants come afterwards.
-- =====================================================================
drop view if exists public.assets_with_status;

create view public.assets_with_status
with (security_invoker = on) as
select
  a.*,
  public.asset_status(a.device_type, a.date_cleaned, a.next_clean_due) as status,
  (a.next_clean_due - current_date)                                    as days_until_due
from public.assets a;

comment on view public.assets_with_status is 'assets + derived status/days_until_due. Read-only surface for the app.';


-- =====================================================================
-- 8. Row Level Security
--    Every signed-in member of the IT team shares one dataset. Anonymous
--    visitors get nothing at all, which is what makes it safe to ship the
--    anon key in the browser bundle.
-- =====================================================================
alter table public.assets       enable row level security;
alter table public.cleaning_log enable row level security;

drop policy if exists "assets_select_authenticated" on public.assets;
create policy "assets_select_authenticated"
  on public.assets for select
  to authenticated
  using (true);

drop policy if exists "assets_insert_authenticated" on public.assets;
create policy "assets_insert_authenticated"
  on public.assets for insert
  to authenticated
  with check (true);

drop policy if exists "assets_update_authenticated" on public.assets;
create policy "assets_update_authenticated"
  on public.assets for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "assets_delete_authenticated" on public.assets;
create policy "assets_delete_authenticated"
  on public.assets for delete
  to authenticated
  using (true);

-- Optional hardening: to restrict deletes to named admins, replace the delete
-- policy above with something like
--   using (auth.jwt() ->> 'email' in ('alice@example.com', 'bob@example.com'));

-- History is readable by everyone signed in and written only by the trigger
-- above, which runs as its owner. Nobody edits or deletes history through the
-- app - that is the point of a log.
drop policy if exists "cleaning_log_select_authenticated" on public.cleaning_log;
create policy "cleaning_log_select_authenticated"
  on public.cleaning_log for select
  to authenticated
  using (true);

revoke all on public.assets             from anon;
revoke all on public.assets_with_status from anon;
revoke all on public.cleaning_log       from anon;

grant select, insert, update, delete on public.assets              to authenticated;
grant select                         on public.assets_with_status  to authenticated;
grant select                         on public.cleaning_log        to authenticated;
grant execute on function public.asset_status(text, date, date)    to authenticated;


-- =====================================================================
-- 9. Realtime: push changes to every open browser tab, so two people
--    editing at once see each other's work without refreshing.
-- =====================================================================
do $$
begin
  alter publication supabase_realtime add table public.assets;
exception
  when duplicate_object then null;
  when undefined_object then null;  -- publication missing (self-hosted); ignore
end;
$$;

-- Realtime also needs the old row to identify deletes under RLS.
alter table public.assets replica identity full;


-- =====================================================================
-- Done. Check it worked:
--
--   select count(*) from public.assets;
--   select status, count(*) from public.assets_with_status group by status order by 1;
--   select cleaned_on, asset_ref, cleaned_by from public.cleaning_log
--     order by cleaned_on desc limit 10;
--
-- Then create your team's accounts under Authentication -> Users (tick
-- "Auto Confirm User"), and turn off public sign-ups under
-- Authentication -> Providers -> Email.
-- =====================================================================
